#!/bin/sh

# Helpers for preserving operator-authored START_PRINT files without keeping
# timestamped copies of files generated by this installer.

start_print_is_managed() {
    candidate=$1
    source_file=$2

    [ -L "$candidate" ] && return 0
    cmp -s "$candidate" "$source_file" 2>/dev/null && return 0
    grep -qE '^[[:space:]]*# === BEGIN surface-selection wrapper' \
        "$candidate" 2>/dev/null &&
        grep -qE '^[[:space:]]*# === END surface-selection wrapper' \
            "$candidate" 2>/dev/null
}

backup_unmanaged_start_print() {
    target=$1
    source_file=$2
    suffix=$3

    [ -f "$target" ] || return 0
    start_print_is_managed "$target" "$source_file" && return 0

    backup="${target}.${suffix}"
    cp -p "$target" "$backup"
    echo "I: preserved custom START_PRINT at $backup"
}

cleanup_managed_start_print_backups() {
    target=$1
    source_file=$2

    for candidate in \
        "${target}.before-surface-wrapper-"* \
        "${target}.before-material-z-offsets."*; do
        [ -f "$candidate" ] || continue
        # Delete only byte-for-byte reproducible copies. A backup containing
        # operator edits is retained even if it also carries managed markers.
        if cmp -s "$candidate" "$source_file" 2>/dev/null ||
           cmp -s "$candidate" "$target" 2>/dev/null; then
            rm -f "$candidate"
            echo "I: removed redundant managed START_PRINT backup $candidate"
        fi
    done
}
